inventory/urls.py
from django.conf.urls import url
from . import views

app_name = 'inventory'

urlpatterns = [

    # /inventory/
    url(r'^$', views.index, name='index'),

    # /inventory/<item_id>/borrow/
    url(r'^search/$', views.item_search, name='search'),

    # /inventory/<item_id>
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    # /inventory/<item_id>/borrow/
    url(r'^(?P<pk>[0-9]+)/borrow/$', views.borrow, name='borrow'),

    # /inventory/<username>/            Stores user's username
    url(r'^user/(?P<username>[\w.@+-]+)/$', views.user_items, name='user_items'),

    # /inventory/<username>/csv/        Export user's history to csv
    url(r'^user/(?P<username>[\w.@+-]+)/csv/$', views.csv_export, name='csv'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from inventory import views

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inventory/', include('inventory.urls')),

    # Register
    url(r'^register/$', views.register, name='register'),

    # Login
    url(r'^login/$', login, {'template_name': 'inventory/login_form.html'}, name='login'),

    # Logout
    url(r'^logout/$', logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User


# CSI, Unison, Erick, etc.
class Owner(models.Model):

    owner_name = models.CharField(max_length=45)

    def __str__(self):
        return self.owner_name


# Item table
class Item(models.Model):

    # Columns
    item_name = models.CharField(max_length=85)
    item_description = models.CharField(max_length=250)
    available_count = models.PositiveIntegerField()
    current_borrowed = models.PositiveIntegerField(default=0)
    times_borrowed = models.PositiveIntegerField(default=0)
    item_owner = models.ForeignKey(Owner)

    # Less than 34% of items available to borrow.
    def few_left(self):
        total = self.available_count + self.current_borrowed
        avail = self.available_count
        return avail / total * 100 < 34

    # Between 34-67% of items available to borrow.
    def normal_left(self):
        total = self.available_count + self.current_borrowed
        avail = self.available_count
        return 34 <= avail / total * 100 < 67

    # More than 67% of items available to borrow.
    def many_left(self):
        total = self.available_count + self.current_borrowed
        avail = self.available_count
        return avail / total * 100 >= 67

    def none_left(self):
        return self.available_count == 0

    def __str__(self):
        return '{} - Disponibles:{}, Borrowed: {}'.format(self.item_name, self.available_count, self.current_borrowed)


# Each individual item (will have it's own ID and shit.)
class IndividualItem(models.Model):
    item = models.ForeignKey(Item)
    is_borrowed = models.BooleanField(default=False)

    def __str__(self):
        return '{} ..... ID: {}..... Borrowed={}.'.format(self.item.item_name, self.pk, self.is_borrowed)


def item_directory_path(instance, filename):
        # for imges be uploaded to MEDIA_ROOT/item_<id>/<filename>
        return 'item_{0}/{1}'.format(instance.item.id, filename)


# Cada item va a tener un set de multiples imagenes.
class ItemImages(models.Model):

    item = models.ForeignKey(Item)
    img = models.ImageField(upload_to=item_directory_path)  # uploads to MEDIA/item_id/<img_path>

    def __str__(self):
        return self.item.item_name


# Relates to IndividualItem on a 1-1 relationship.
class ItemBorrowed(models.Model):

    item = models.ForeignKey(IndividualItem)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    date_borrowed = models.DateField(auto_now=True)

    # Date returned initializes to null so that we can change it once the item is returned.
    is_returned = models.BooleanField(default=False)
    date_returned = models.DateField(null=True, blank=True)

    def __str__(self):
        return '{} se llevo un/a {} con id={}........ {} se ha devuelto.'\
            .format(self.user, self.item.item.item_name, self.item.id, 'SI' if self.is_returned else 'NO')


# User shit
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


# Temporary storage... thinking about moving this model to seperate app to
# keep all the relevant shit in it's group and modularity.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(null=True, blank=True, upload_to=user_directory_path)

    def __str__(self):
        return self.user.username


# For the IndividualItem creation.
from .signals import create_individual_item
# For User object creation => UserProfile
# from .signals import create_user_profile, save_user_profile

inventory/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

# All this shit is something that could be moved to seperate app (for modularity).


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['pic']

        labels = {
            'pic': 'Profile Pic',
        }

inventory/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext

from .models import Item, ItemBorrowed, UserProfile
from .forms import UserForm, UserProfileForm
from django.db.models import Q
import csv
from django.core.mail import send_mail  # For email sending


# Function for re-using of pagination feature in different views.
def paginate(page, paginator, queryset):
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    return queryset


# For /inventory/
@login_required
def index(request):
    items = Item.objects.all().order_by('-times_borrowed')
    paginator = Paginator(items, 12)

    page = request.GET.get('page')
    items = paginate(page, paginator, items)

    context = {'items': items}

    return render(request, 'inventory/item_list.html', context)


# Search item
@login_required
def item_search(request):
    items = Item.objects.all().order_by('-times_borrowed')

    # For search form
    query = request.GET.get('q')
    if query:
        items = Item.objects.filter(
            Q(item_name__icontains=query)
        ).distinct()

    paginator = Paginator(items, 12)
    page = request.GET.get('page')
    items = paginate(page, paginator, items)

    context = {'items': items, 'query': query}

    return render(request, 'inventory/item_list.html', context)


# pk = item_id
@login_required
def detail(request, pk):
    try:
        item = Item.objects.get(pk=pk)
    except Item.DoesNotExist:
        raise Http404('Item doesn\'t exist.')

    images = item.itemimages_set.all()[1:]

    context = {
        'item': item,
        'images': images,
    }

    return render(request, 'inventory/item_detail.html', context)


# pk = item_id
@login_required
def borrow(request, pk):
    try:
        item = Item.objects.get(pk=request.POST['item'])
    except Item.DoesNotExist:
        raise Http404('Item doesn\'t exist.')

    else:

        all_unborrowed_items = item.individualitem_set.filter(is_borrowed=False)

        # If there are no unborrowed items, the button to borrowe will be disabled (won't even go through to this view)

        # Gets the first item that's not borrowed yet.
        unborrowed_individual_item = all_unborrowed_items[0]

        # Change the unborrowerd to borrowed = True
        unborrowed_individual_item.is_borrowed = True
        unborrowed_individual_item.save()

        # Creating new ItemBorrowed object
        borrowed = ItemBorrowed(item=unborrowed_individual_item, user=request.user)
        borrowed.save()

        # Changing general item's attributes
        item.available_count -= 1
        item.current_borrowed += 1
        item.times_borrowed += 1

        item.save()

        # Whenever borrowed item, send email
        send_mail(
            '{} has borrowed a {}'.format(request.user, item.item_name),
            'Item ID: {}'.format(unborrowed_individual_item.id),
            'noreply@erickdelfin.me',
            ['e_delfin_23@yahoo.com'],
            fail_silently=False
        )

        return render(request, 'inventory/admin.html', {'individual_item': unborrowed_individual_item})


# username = username gotten from user_items urlpattern
@login_required
def user_items(request, username):
    user = User.objects.get(username=username)

    borrowed_items = ItemBorrowed.objects.filter(user=user, is_returned=False)
    history = ItemBorrowed.objects.filter(user=user, is_returned=True)

    total = len(borrowed_items) + len(history)
    current_borrowed = len(borrowed_items)
    history_count = len(history)

    return render(request, 'inventory/user_items.html', {
        'borrowed_items': borrowed_items,
        'history': history,
        'user': user,
        'total': total,
        'current': current_borrowed,
        'history_count': history_count,
    })


# Export feature for user profile (exports user's registers to csv)
@login_required
def csv_export(request, username):
    user = User.objects.filter(username=username)
    registers = ItemBorrowed.objects.filter(user=user)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="{}.csv"'.format(username)

    writer = csv.writer(response)
    # CSV Header
    writer.writerow([
        'Item',
        'Date Borrowed',
        'Is Returned?',
        'Date Returned'
    ])
    # Rows
    for obj in registers:
        writer.writerow([
            obj.item.item.item_name,
            obj.date_borrowed,
            obj.is_returned,
            obj.date_returned,
        ])

    return response


# For user register
def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready, to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'pic' in request.FILES:
                profile.pic = request.FILES['pic']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

            # Login the user
            login(request, user)
            return HttpResponseRedirect("/inventory/")

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors, profile_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    # IN THIS CASE, IT MEANS IT's A 'GET' REQUEST. (See if statement on top = 'POST')
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                  'inventory/registration.html', {
                       'user_form': user_form,
                       'profile_form': profile_form,
                       'registered': registered
                  },
                  context)

templates/inventory/admin.html
{% extends 'inventory/base.html' %}
{% block title %}Borrow{% endblock %}

{% block body_block %}

    <div class="section"></div>
    <div class="section"></div>

    <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s12 center-align">
                    <h4>Go to <a href="{% url 'inventory:user_items' 'admin' %}">Erick</a> (Admin) to pick up your <a href="{% url 'inventory:detail' individual_item.item.id %}">{{ individual_item.item.item_name }}</a>!</h4>
                    <h6>Once your done with your {{ individual_item.item.item_name }}, head over to Erick and return it.</h6>

                    <div class="section"></div>
                    <div class="section"></div>

                    <h4>Your Item ID:</h4>
                    <div class="row">
                        <div class="col s12 m4 offset-m4">
                            <div class="card deep-purple lighten-2">
                                <div class="card-content white-text">
                                    <h3>{{ individual_item.id }}</h3>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="section"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="s12" style="display: inline">

            <a href="{% url 'inventory:index' %}" class="waves-effect waves-light btn-large deep-purple lighten-2 right" style="margin-left: 10px !important;">
                <i class="fa fa-home"></i> Go Home
            </a>

            <a href="{% url 'inventory:user_items' request.user.username %}" class="waves-effect waves-light btn-large deep-purple lighten-2 right">
                <i class="fa fa-list-alt"></i> My Profile
            </a>

        </div>
    </div>

    <div class="section"></div>
    <div class="section"></div>

{% endblock %}

templates/inventory/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Loads the path to that static files -->
    {% load staticfiles %}

    <title> {% block title %}CSInventory{% endblock %} </title>
    <link rel="icon" href="{% static 'inventory/img/favicon.ico' %}" type="image/x-icon">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pattaya" rel="stylesheet">

    {#-----------------------------------------CSS-----------------------------------------------------#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.min.css">
    <link rel="stylesheet" href="{% static 'inventory/css/style.css' %}?v=0005" type="text/css">
    {#-----------------------------------------/CSS-----------------------------------------------------#}

    {#-----------------------------------------SCRIPTS-----------------------------------------------------#}
    <!--Import jQuery before materialize.js-->
    <script src="https://cdn.jsdelivr.net/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/lightgallery/1.3.9/js/lightgallery.min.js"></script>
    {#-----------------------------------------/SCRIPTS-----------------------------------------------------#}

    {% block styles %}
        {# Custom styles #}
    {% endblock %}

</head>

<!-- Preloader -->
<script type="text/javascript">
    $(window).on('load', function() { // makes sure the whole site is loaded
        $('#status').fadeOut(); // will first fade out the loading animation
        $('#preloader').delay(350).fadeOut('slow');
        $('body').delay(350).css({'overflow':'visible'});
      });
</script>

<body>

    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>

    <header>

        {# NAVBAR #}
        <nav>
            <div class="nav-wrapper deep-purple lighten-2">

            <div class="container">

                <a href="{% url 'inventory:index' %}" class="brand-logo">CSInventory</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'inventory:index' %}"><i class="fa fa-home"></i> Home</a></li>

                    {% if request.user.is_authenticated %}
                        <li><a class="dropdown-button" href="#" data-activates="dropdown1" data-beloworigin="true">
                            <i class="fa fa-user"></i>
                            {{ request.user.username }}
                            <i class="material-icons right">arrow_drop_down</i>
                        </a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Log in</a></li>
                    {% endif %}

                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="dropdown-content">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'inventory:user_items' request.user.username %}"><i class="fa fa-list-alt"></i> Profile</a></li>
                        {% endif %}
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}?next=/login"><i class="fa fa-sign-out"></i> Log out</a></li>
                    </ul>

                </ul>

                {# Search form #}
                <form action="{% url 'inventory:search' %}" method="get">
                {% csrf_token %}
                    <div class="input-field right hide-on-med-and-down">
                        <i class="material-icons prefix" style="color: white;">search</i>
                        <input id="icon_prefix" name="q" type="text" value="{{ request.GET.q }}" class="validate search-validate">
                        <label for="icon_prefix" style="color: white;">Search</label>
                    </div>
                </form>

            </div>

            <ul class="side-nav" id="mobile-demo">
                <li>
                    {# Side-nav search bar #}
                    <form action="{% url 'inventory:search' %}" method="get">
                    {% csrf_token %}
                    <div class="input-field">
                            <i class="material-icons prefix" style="color: black;">search</i>
                            <input id="icon_prefix" name="q" type="text" value="{{ request.GET.q }}" class="validate search-validate" style="color: black">
                            <label for="icon_prefix" style="color: black">Search</label>
                        </div>
                    </form>
                </li>
                <li><a href="{% url 'inventory:index' %}" class="waves-effect waves-purple"><i class="fa fa-2x fa-home"></i> Home</a></li>

                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            {% if request.user.is_authenticated %}
                                <a href="#" class="collapsible-header waves-effect waves-purple">
                                    <i class="fa fa-user"></i> {{ request.user.username }}
                                    <i class="material-icons right">arrow_drop_down</i>
                                </a>
                            {% else %}
                                <a href="{% url 'login' %}"><i class="fa fa-2x fa-sign-in"></i> Log in</a>
                            {% endif %}

                            <div class="collapsible-body">
                                <ul>
                                    {% if request.user.is_authenticated %}<li><a href="{% url 'inventory:user_items' request.user.username %}">Profile</a></li>{% endif %}
                                    <li><a href="{% url 'logout' %}?next=/login">Log out</a></li>
                                </ul>
                            </div>

                        </li>
                    </ul>
                </li>
            </ul>
            </div>
        </nav>
    {# /NAVBAR #}

    </header>



    <main>

        <div class="container">

            {% block body_block %}
                {# Content ~ #}
            {% endblock %}

        </div>

    </main>


<footer class="page-footer deep-purple lighten-2">
    <div class="container">
        <div class="row">
            <div class="col m12 s12 footer-content center-align">
                <h5 class="white-text"><img src="{% static 'inventory/img/logo.png' %}" alt="CSInventory" height="45px"></h5>
                <div class="social">
                    <a href="https://github.com/CSIPro" target="_blank"><i class="fa fa-github"></i></a>
                    <a href="https://twitter.com/CSIPro_Dev" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="https://www.facebook.com/CsiProUnison/" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="mailto:csipro.dev@gmail.com"><i class="fa fa-envelope"></i></a>
                </div>
            </div>
        </div>
    </div>
{#    <div class="footer-copyright">#}
{#        <div class="container center-align">#}
{#            © 2017 Copyright CSIPro#}
{#        </div>#}
{#    </div>#}
</footer>





    <script src="{% static 'inventory/js/index.js' %}" type="text/javascript"></script>

</body>

</html>

templates/inventory/item_list.html
{% extends 'inventory/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div class="section"></div>
    <div class="section"></div>

        <div class="row">

        {% if items %}
            {% if query %}
                <h5>Results for <a>"{{ query }}"</a>.</h5>
            {% endif %}

            {% for item in items %}

                <div class="col s12 m4 cardCol">
                    <div class="card item-card z-depth-3">
                        <div class="card-image">

                            <img class="materialboxed" src="{{ item.itemimages_set.all.first.img.url }}">

                            <a href="{% url 'inventory:detail' item.id %}" class="waves-effect waves-light btn-floating halfway-fab waves-effect waves-light deep-purple lighten-2"><i class="material-icons">add</i></a>
                        </div>
                        <div class="card-action item-action">

                            <a class="truncate" href="{% url 'inventory:detail' item.id %}"><i class="fa fa-rocket" aria-hidden="true"></i> {{ item.item_name }}</a>
                            <i class="fa fa-check-circle-o" aria-hidden="true"></i>
                            <p class="available-count {% if item.many_left %}border-green{% elif item.normal_left %}border-yellow{% else %}border-red{% endif %}">{{ item.available_count }}</p>

                        </div>
                    </div>

                    <div class="text-owner">
                        <p><i class="fa fa-smile-o" aria-hidden="true"></i> <strong>{{ item.item_owner.owner_name }}</strong></p>
                    </div>
                </div>

            {% endfor %}

            <div class="row">
                <div class="col s12 right-align">

                    <ul class="pagination">
                        {% if items.has_previous %}
                            <li class="waves-effect"><a href="?page={{ items.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                        {% else %}
                            <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
                        {% endif %}

                        {% for x in items.paginator.page_range %}
                            {% if items.number == x %}
                                <li class="active deep-purple lighten-2"><a>{{ x }}</a></li>
                            {% else %}
                                <li class="waves-effect"><a href="?page={{ x }}">{{ x }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if items.has_next %}
                            <li class="waves-effect"><a href="?page={{ items.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                        {% else %}
                            <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
                        {% endif %}
                    </ul>

                </div>
            </div>

        {% else %}

            <!-- Empty search result -->
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12 center-align">
                            <h5 class="truncate">No results were found for <a>"{{ query }}"</a> :(</h5>
                            <a href="{% url 'inventory:index' %}" class="waves-effect waves-light btn-large deep-purple lighten-2">
                                <i class="fa fa-home"></i> Go Home
                            </a>
                            <h5>or edit your search query.</h5>
                        </div>
                    </div>
                </div>
            </div>

        {% endif %}

        </div>


{% endblock %}

templates/inventory/login_form.html
{% extends 'inventory/base.html' %}
{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block body_block %}

    <main>

        <div class="container">

{% if user.is_authenticated %}

            <div class="row">
                <div class="section"></div>
                <div class="section"></div>

                <div class="header-text col s12 m6 offset-m3" style="">
                    <img class="responsive-img" src="{% static 'inventory/img/csi.png' %}" />
                </div>

                <div class="card col s12 m6 offset-m3 z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                    <h5>User <a href="{% url 'inventory:user_items' user.username %}">{{ user.username }}</a> is currently logged in.</h5>

                    <div class="section"></div>
                    <div class='row'>
                        <a href="{% url 'logout' %}?next=/login" class='col s12 btn btn-large waves-effect btn-submit'>Logout</a>
                    </div>

                </div>


            </div>

{% else %}

            <div class="row">
                <div class="section"></div>
                <div class="section"></div>

                <div class="header-text col s12 m6 offset-m3" style="">
                    <img class="responsive-img" src="{% static 'inventory/img/csi.png' %}" />

                    <h5 class="center-align">Log in to your account.</h5>
                </div>

                <div class="card col s12 m6 offset-m3 z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0 48px; border: 1px solid #EEE;">
                    {% if form.errors %}
                        <p class="pink-text">Your username and password didn't match. Please try again.</p>
                    {% endif %}

                    <form class="col s12" method="post">
                        {% csrf_token %}

                        {% for field in form %}

                        <div class='row'>
                            <div class='input-field col s12'>
                                {# <input class='validate' type='email' name='email' id='email' />#}
{#                              <input class="validate" id="{{ field.id_for_label }}" maxlength="30" name="{{ field.html_name }}" type="password" />#}
                                {{ field }}

                                <label for="{{ field.id_for_label }}">{{ field.html_name }}</label>
                            </div>
                        </div>

                        {% endfor %}

{#                        <label>#}
{#                            <a class='pink-text' href='#!'><b>Forgot Password?</b></a>#}
{#                        </label>#}

                        <div class='row'>
                            <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect btn-submit'>Login</button>
                        </div>
                    </form>
                </div>

            </div>

{% endif %}

        </div>
        <div class="section"></div>
    </main>

{% endblock %}